### PR TITLE
marshals set type

### PR DESCRIPTION
**Pull request by TimothyZhang**
#53 complains that set type is not well marshalled. I figured out it's because python str representation of set type is not what cassandra needs.
python str() produces:
```
>>> s = {1, 2, 3}
>>> str(s)
'set([1, 2, 3])'
```
but cassandra wants `{1, 2, 3}`. So we have to marshal set elements one by one.

### CODE REVIEW

**Comment by cyli** [comment]
Hi @TimothyZhang!  Wow, thanks for picking this up!  I was going to try to do this later - awesome :D  This LGTM, except there's a merge conflict - I think you may have to remerge this repo's master (not your fork's master) into this branch?

**Comment by TimothyZhang** [comment]
hi @cyli I resolved the conflict. And also added code to marshal `set` type, originally only `sortedset` was marshaled, but I think `set` should be marshaled too.

**Comment by TimothyZhang** [comment]
Fixes #53

**Comment by cyli** [comment]
@TimothyZhang Awesome, thank you!  LGTM.

**Pull request merged**
